#ifndef QMAINDEFINITIONS_H
#define QMAINDEFINITIONS_H

#define PAN_WIDTH 640
#define PAN_HEIGHT 480

#define FOVEAL_WIDTH 640
#define FOVEAL_HEIGHT 480

#define PAN_DISPLAY 0
#define FOVEAL_DISPLAY 1


#endif // QMAINDEFINITIONS_H
